language: cpp
os: linux
dist: xenial
branches:
  except:
    - master # Skip building master since updating the README.md doesn't need to trigger a new build
env:
  # Change the definitions if your binary or source folder are different
  - SRC_DIR=src TRIPLET_CHALLENGE="./triplet_challenge pg2009.txt"
addons:
  apt:
    sources:
      # Include here any new source that you may need to install a package
      - ubuntu-toolchain-r-test # remove if not using g++ for C++
    packages:
      # Include the specific packages that you need
      - g++-8

# Modify the script lines to compile and program
script:
  # Take a look at https://github.com/pamarcos/triplet_challenge/blob/cpp/.travis.yml to see a full example of a C++ build
  - export CXX=g++-8
  - $CXX --version
  - make
  - make check
  - wget https://raw.githubusercontent.com/pamarcos/triplet_challenge/master/check_result.sh && bash check_result.sh

# Do not change the `after_success` lines since they are used to collect results to compare with other implementations
after_success:
  - wget https://raw.githubusercontent.com/pamarcos/triplet_challenge/master/after_success.sh && bash after_success.sh
